MessageView: improve styling of presence status
Nheko-Reborn/nheko pull request #1379
Opened 2023-02-16 15:52 UTC by Bubu

Put the status in parenthesis, which is the usual presentation for a user status i.e. UserX (Away).

Also significantly reduce the font size as to visually indicate this is additional information and not part of the username or message text.

2023-02-16 15:57 UTC, Bubu commented
Still undecided between 0.75 and 0.8 scaling factor.  :D

2023-02-16 16:27 UTC, deepbluev7 commented
I would probably leave out the () :)

2023-02-16 16:27 UTC, deepbluev7 commented
And afaik we use 0.8 elsewhere, but you might want to Math.floor it

2023-02-16 17:09 UTC, LorenDB commented
> I find that almost the more important part of this commit tbh. It's how people already encode their status into the nickname currently and is how ICQ did it many years back as well. 🤷 (To clarify: Icq had proper statuses, but when displaying it I remember it always being in parenthesis behind the nickname)

IMO if you are going to modify what the status message shows, it should be limited to prepending "Status: " to the status. But I think that it is fairly obvious that the status message is a status message already, so you really shouldn't have to modify it. Alternately, you could just add a tooltip that says something about this being a status.

2023-02-16 22:07 UTC, Bubu commented
I removed the parentheses, added a hover text and added the status message text to the userprofile page.

2023-02-16 23:13 UTC, LorenDB requested changes
This looks good overall to me.

2023-02-16 23:13 UTC, LorenDB commented on resources/qml/dialogs/UserProfile.qml
> +            spacing: 8
Can you make this one of the paddings specified in NhekoGlobalObject.h?

2023-02-16 23:26 UTC, Bubu commented on resources/qml/MessageView.qml
> +                            id: status_label_hover_handler
heh, python casing slipped in here, I'll change that for consistency :)

2023-02-16 23:29 UTC, LorenDB approved these changes
LGTM

2023-02-16 23:47 UTC, deepbluev7 commented
> I've seen many examples in the codebase that don't do this. What's the benefit of adding it?

I have seen alignment break horribly when you get some crooked font sizes, that are not a multiple of 0.5. It probably isn't needed, I guess I should investigate more, why I originally added that.

2023-02-21 00:41 UTC, deepbluev7 commented
![grafik](https://user-images.githubusercontent.com/16312324/220219504-d64257a1-438d-48b4-b811-1e4d5ffef0d7.png)

![grafik](https://user-images.githubusercontent.com/16312324/220219603-0eba492d-e730-405c-bc62-40a0d6b94d40.png)

I think I found a bug

2023-02-21 00:46 UTC, deepbluev7 commented on resources/qml/dialogs/UserProfile.qml
> +                Layout.alignment: Qt.AlignHCenter
```suggestion
                Layout.alignment: Qt.AlignHCenter
                Layout.fillWidth: true
                horizontalAlignment: TextEdit.AlignHCenter
```

2023-02-21 00:46 UTC, deepbluev7 commented
Otherwise it looks good to me :3

2023-02-21 22:21 UTC, deepbluev7 commented
Thank you!

2023-02-21 22:21 UTC, merged