Add dialog for repeating password when exporting keys
Nheko-Reborn/nheko pull request #1734
Opened 2024-05-19 20:24 UTC by Integral-Tech

Related issue: https://github.com/Nheko-Reborn/nheko/issues/1729

2024-05-26 02:08 UTC, uwnuk commented
I suggest considering whether to have it compare passwords upon every character entry.
Maybe it's not the best idea - I do understand that nheko aims to be fast, and this could be more complicated, however it can offer a better user experience in some cases.

2024-05-26 02:13 UTC, uwnuk commented on src/UserSettingsPage.cpp
> +
We may want to warn that the repeated password is empty if they've entered a password.
This should be obvious to the end user anyways, but
```suggestion
    if (password.isEmpty()) {
        QMessageBox::warning(nullptr, tr("Error"), tr("The password cannot be empty"));
        return;
    }

    if (repeatedPassword.isEmpty()) {
        QMessageBox::warning(nullptr, tr("Error"), tr("Please repeat the password"));
        return;
    }

    if (password != repeatedPassword) {
        QMessageBox::warning(nullptr, tr("Error"), tr("Passwords don't match"));
        return;
    }

```

2024-05-26 02:22 UTC, Integral-Tech commented
@uwnuk Thanks for your suggestion

2024-06-12 05:48 UTC, Integral-Tech commented
@deepbluev7

2024-06-16 20:33 UTC, deepbluev7 requested changes
Most looks fine, but I think there are some small behavioural things, that could be improved. Thank you for the contribution!

2024-06-16 20:33 UTC, deepbluev7 commented on src/UserSettingsPage.cpp
>      }
Can you move this check up to behind the first dialog? There is no need to ask the user for a second password, if the first one is invalid.

2024-06-16 20:33 UTC, deepbluev7 commented on src/UserSettingsPage.cpp
> +    }
This check is unnecessary, if the password was already tested for being empty and password and repeatedPassword have to be the same. You can remove it.

2024-06-17 03:01 UTC, Integral-Tech commented
@deepbluev7 Solved :)

2024-06-17 03:01 UTC, deepbluev7 commented
Sorry, but I don't know what that command means.

Thanks for asking 🥰

2024-06-17 15:33 UTC, Integral-Tech commented
@deepbluev7 The pipeline on GitLab seems to failed :(

2024-06-17 15:33 UTC, deepbluev7 commented
Sorry, but I don't know what that command means.

Thanks for asking 🥰

2024-06-20 20:04 UTC, deepbluev7 commented
Seems to work now and looks pretty good,thank you!

2024-06-20 20:05 UTC, merged