Change the font box to QFontComboBox as per issue 238
Nheko-Reborn/nheko pull request #303
Opened 2020-10-20 00:41 UTC by LorenDB

This PR dedicated to @deepbluev7 for the major help with libs, cmake, and limited Wifi.

2020-10-20 16:28 UTC, utkarsh2102 requested changes
Hello,

Thanks a ton for working on this! ❤️ 
However, could you please attach a screenshot or something of the list of fonts that are displayed after building nheko on top of this PR?

Besides, I do have a minor suggestion comment below and there is also a merge conflict 😄

2020-10-20 16:28 UTC, utkarsh2102 commented on src/UserSettingsPage.cpp
> +        // }
I feel it's best to remove the lines of code that are not needed instead of commenting out?

2020-10-20 19:03 UTC, LorenDB commented
Yeah, I will remove the comments and squash the commit. Screenshot attached. ![20201019_203111_929599009838574618_20201020150215.jpg](https://user-images.githubusercontent.com/55629213/96632213-62d6ff00-12e5-11eb-8ba4-aec1978b87b0.jpg)

2020-10-20 19:12 UTC, utkarsh2102 commented
In that case, this looks awesome! ❤️

2020-10-21 21:17 UTC, LorenDB commented
All errors/weird diffs/etc. have been resolved. Ready to merge AFAIK.

2020-10-21 22:31 UTC, merged

2020-10-21 22:31 UTC, deepbluev7 commented
Thank you, awesome work!

2020-10-21 22:33 UTC, LorenDB commented
> Thank you, awesome work!

Thank **you** too :D